const PARTS = [
  {
    name: "VP-66EG Stun Gun",
    img: "VP-66EG Stun Gun.webp",
    tier: "c",
    category: "r-arm",
  },
  {
    name: "VVC-70VPM",
    img: "vvc-70vmp.webp",
    tier: "c",
    category: "r-back",
  },
  {
    name: "VVC-70VPM",
    img: "vvc-70vmp.webp",
    tier: "c",
    category: "l-back",
  },
  {
    name: "IA-C01W6: NB-REDSHIFT Coral Rifle",
    img: "IA-C01W6 NB-REDSHIFT Coral Rifle.webp",
    tier: "s",
    category: "r-arm",
  },
  {
    name: "IB-C03W1: WLT 011 Coral Rifle",
    img: "IB-C03W1 WLT 011 Coral Rifle.webp",
    tier: "s",
    category: "r-arm",
  },
  {
    name: "44-142 KRSV Multi Energy Rifle",
    img: "44-142 KRSV Multi Energy Rifle.webp",
    tier: "s",
    category: "r-arm",
  },
  {
    name: "WS-5000 APERITIF Siege Missile Launcher",
    img: "WS-5000 APERITIF Siege Missile Launcher.webp",
    tier: "s",
    category: "r-arm",
  },
  {
    name: "Vvc-774LS Laser Slicer",
    img: "Vvc-774LS Laser Slicer.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "IA-C01W7: ML-REDSHIFT Coral Oscillator",
    img: "ia-c01w7-ml-redshift.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "IB-C03W2: WLT 101 Coral Oscillator",
    img: "IB-C03W2 WLT 101 Coral Oscillator.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "VP-66EG Stun Gun",
    img: "VP-66EG Stun Gun.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "IA-C01W6: NB-REDSHIFT Coral Rifle",
    img: "IA-C01W6 NB-REDSHIFT Coral Rifle.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "IB-C03W1: WLT 011 Coral Rifle",
    img: "IB-C03W1 WLT 011 Coral Rifle.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "44-142 KRSV Multi Energy Rifle",
    img: "44-142 KRSV Multi Energy Rifle.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "WS-5000 APERITIF Siege Missile Launcher",
    img: "WS-5000 APERITIF Siege Missile Launcher.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "VE-60LCA Laser Cannon",
    img: "VE-60LCA Laser Cannon.webp",
    tier: "s",
    category: "r-back",
  },
  {
    name: "KRANICH/60Z Pulse Cannon",
    img: "kranich-60z.webp",
    tier: "c",
    category: "r-back",
  },
  {
    name: "WR-0999 DELIVERY BOY Cluster Missile Launcher",
    img: "WR-0999 DELIVERY BOY Cluster Missile Launcher.webp",
    tier: "d",
    category: "r-back",
  },
  {
    name: "WS-5001 SOUP Scatter Missile Launcher",
    img: "WS-5001 SOUP Scatter Missile Launcher.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "EL-PW-01 TRUENO Needle Missile Launcher",
    img: "EL-PW-01 TRUENO Needle Missile Launcher.webp",
    tier: "s",
    category: "r-back",
  },
  {
    name: "IB-C03W3: NGI 006 Coral Missile Launcher",
    img: "IB-C03W3 NGI 006 Coral Missile Launcher.webp",
    tier: "a",
    category: "r-back",
  },
  {
    name: "BO-044 HUXLEY Bullet Orbit",
    img: "BO-044 HUXLEY Bullet Orbit.webp",
    tier: "s",
    category: "r-back",
  },
  {
    name: "VE-61PSA Pulse Scutum",
    img: "ve-61psa.webp",
    tier: "c",
    category: "l-back",
  },
  {
    name: "IB-C03W4: NGI 028 Coral Shield",
    img: "IB-C03W4 NGI 028 Coral Shield.webp",
    tier: "c",
    category: "l-back",
  },
  {
    name: "VE-60LCA Laser Cannon",
    img: "VE-60LCA Laser Cannon.webp",
    tier: "s",
    category: "l-back",
  },
  {
    name: "KRANICH/60Z Pulse Cannon",
    img: "kranich-60z.webp",
    tier: "c",
    category: "l-back",
  },
  {
    name: "WR-0999 DELIVERY BOY Cluster Missile Launcher",
    img: "WR-0999 DELIVERY BOY Cluster Missile Launcher.webp",
    tier: "d",
    category: "l-back",
  },
  {
    name: "WS-5001 SOUP Scatter Missile Launcher",
    img: "WS-5001 SOUP Scatter Missile Launcher.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "EL-PW-01 TRUENO Needle Missile Launcher",
    img: "EL-PW-01 TRUENO Needle Missile Launcher.webp",
    tier: "s",
    category: "l-back",
  },
  {
    name: "IB-C03W3: NGI 006 Coral Missile Launcher",
    img: "IB-C03W3 NGI 006 Coral Missile Launcher.webp",
    tier: "a",
    category: "l-back",
  },
  {
    name: "BO-044 HUXLEY Bullet Orbit",
    img: "BO-044 HUXLEY Bullet Orbit.webp",
    tier: "s",
    category: "l-back",
  },
  {
    name: "HC-2000/BC SHADE EYE",
    img: "hc-2000-bc-shade-eye.webp",
    tier: "s",
    category: "head",
  },
  {
    name: "HS-5000 APPETIZER",
    img: "HS-5000 APPETIZER.webp",
    tier: "s",
    category: "head",
  },
  {
    name: "20-082 MIND BETA",
    img: "20-082 MIND BETA.webp",
    tier: "s",
    category: "head",
  },
  {
    name: "CS-5000 MAIN DISH",
    img: "CS-5000 MAIN DISH.webp",
    tier: "s",
    category: "core",
  },
  {
    name: "AS-5000 SALAD",
    img: "AS-5000 SALAD.webp",
    tier: "s",
    category: "arms",
  },
  {
    name: "2S-5000 DESSERT",
    img: "2S-5000 DESSERT.webp",
    tier: "s",
    category: "legs",
  },
  {
    name: "BC-0200 GRIDWALKER",
    img: "BC-0200 GRIDWALKER.webp",
    tier: "c",
    category: "booster",
  },
  {
    name: "IB-C03B: NGI 001",
    img: "IB-C03B NGI 001.webp",
    tier: "a",
    category: "booster",
  },
  { name: "VE-20B", img: "ve-20b.webp", tier: "a", category: "generator" },
  {
    name: "WR-0555 ATTACHE Heavy Machine Gun",
    img: "WR-0555 ATTACHE Heavy Machine Gun.webp",
    tier: "a",
    category: "r-arm",
  },
  {
    name: "EL-PW-00 VIENTO Needle Gun",
    img: "EL-PW-00 VIENTO Needle Gun.webp",
    tier: "a",
    category: "r-arm",
  },
  {
    name: "DIZZY Grenade Launcher",
    img: "dizzy.webp",
    tier: "a",
    category: "r-arm",
  },
  {
    name: "VE-66LRB Laser Rifle",
    img: "VE-66LRB Laser Rifle.webp",
    tier: "a",
    category: "r-arm",
  },
  {
    name: "HML-G3/P08SPL-06 Split Missile Launcher",
    img: "hml-g3-p08spl-06.webp",
    tier: "a",
    category: "r-arm",
  },
  {
    name: "VP-67LD Laser Dagger",
    img: "vp-67ld.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "IA-C01W2: MOONLIGHT Light Wave Blade",
    img: "ia-c01w2-moonlight.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "WR-0555 ATTACHE Heavy Machine Gun",
    img: "WR-0555 ATTACHE Heavy Machine Gun.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "EL-PW-00 VIENTO Needle Gun",
    img: "EL-PW-00 VIENTO Needle Gun.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "DIZZY Grenade Launcher",
    img: "dizzy.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "VE-66LRB Laser Rifle",
    img: "VE-66LRB Laser Rifle.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "HML-G3/P08SPL-06 Split Missile Launcher",
    img: "hml-g3-p08spl-06.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "EARSHOT Grenade Cannon",
    img: "earshot.webp",
    tier: "a",
    category: "r-back",
  },
  {
    name: "VE-60LCB Laser Cannon",
    img: "ve-60lcb.webp",
    tier: "a",
    category: "r-back",
  },
  {
    name: "FASAN/60E Plasma Cannon",
    img: "fasan-60e.webp",
    tier: "a",
    category: "r-back",
  },
  {
    name: "IA-C01W3: AURORA Light Wave Cannon",
    img: "ia-c01w3-aurora.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "BML-G2/P19SPL-12 Split Missile Launcher",
    img: "bml-g2-p19spl-12.webp",
    tier: "c",
    category: "r-back",
  },
  {
    name: "BML-G2/P08DUO-03 Dual Missile Launcher",
    img: "bml-g2-p08duo-03.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "BML-G1/P07VTC-12 Vertical Missile Launcher",
    img: "bml-g1-p07vtc-12.webp",
    tier: "d",
    category: "r-back",
  },
  {
    name: "BML-G1/P29CNT Container Missile Launcher",
    img: "bml-g1-p29cnt.webp",
    tier: "d",
    category: "r-back",
  },
  {
    name: "45-091 ORBT Laser Orbit",
    img: "45-091-orbt.webp",
    tier: "a",
    category: "r-back",
  },
  {
    name: "Vvc-700LD Laser Drone",
    img: "vvc-700ld.webp",
    tier: "a",
    category: "r-back",
  },
  {
    name: "EARSHOT Grenade Cannon",
    img: "earshot.webp",
    tier: "a",
    category: "l-back",
  },
  {
    name: "VE-60LCB Laser Cannon",
    img: "ve-60lcb.webp",
    tier: "a",
    category: "l-back",
  },
  {
    name: "FASAN/60E Plasma Cannon",
    img: "fasan-60e.webp",
    tier: "a",
    category: "l-back",
  },
  {
    name: "IA-C01W3: AURORA Light Wave Cannon",
    img: "ia-c01w3-aurora.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "BML-G2/P19SPL-12 Split Missile Launcher",
    img: "bml-g2-p19spl-12.webp",
    tier: "c",
    category: "l-back",
  },
  {
    name: "BML-G2/P08DUO-03 Dual Missile Launcher",
    img: "bml-g2-p08duo-03.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "BML-G1/P07VTC-12 Vertical Missile Launcher",
    img: "bml-g1-p07vtc-12.webp",
    tier: "d",
    category: "l-back",
  },
  {
    name: "BML-G1/P29CNT Container Missile Launcher",
    img: "bml-g1-p29cnt.webp",
    tier: "d",
    category: "l-back",
  },
  {
    name: "45-091 ORBT Laser Orbit",
    img: "45-091-orbt.webp",
    tier: "a",
    category: "l-back",
  },
  {
    name: "Vvc-700LD Laser Drone",
    img: "vvc-700ld.webp",
    tier: "a",
    category: "l-back",
  },
  {
    name: "HD-012 MELANDER C3",
    img: "hd-012-melander-c3.webp",
    tier: "a",
    category: "head",
  },
  { name: "VP-44D", img: "vp-44d.webp", tier: "a", category: "head" },
  { name: "VE-44B", img: "ve-44b.webp", tier: "a", category: "head" },
  {
    name: "EL-PH-00 ALBA",
    img: "el-ph-00-alba.webp",
    tier: "a",
    category: "head",
  },
  {
    name: "20-081 MIND ALPHA",
    img: "20-081-mind-alpha.webp",
    tier: "a",
    category: "head",
  },
  {
    name: "IA-C01H: EPHEMERA",
    img: "ia-c01h-ephemera.webp",
    tier: "a",
    category: "head",
  },
  {
    name: "IB-C03H: HAL 826",
    img: "ib-c03h-hal-826.webp",
    tier: "a",
    category: "head",
  },
  {
    name: "BD-012 MELANDER C3",
    img: "bd-012-melander-c3.webp",
    tier: "a",
    category: "core",
  },
  {
    name: "EL-PC-00 ALBA",
    img: "el-pc-00-alba.webp",
    tier: "a",
    category: "core",
  },
  {
    name: "IA-C01C: EPHEMERA",
    img: "ia-c01c-ephemera.webp",
    tier: "a",
    category: "core",
  },
  {
    name: "IB-C03C: HAL 826",
    img: "ib-c03c-hal-826.webp",
    tier: "a",
    category: "core",
  },
  {
    name: "AR-012 MELANDER C3",
    img: "ar-012-melander-c3.webp",
    tier: "a",
    category: "arms",
  },
  { name: "VP-46D", img: "vp-46d.webp", tier: "a", category: "arms" },
  {
    name: "EL-PA-00 ALBA",
    img: "el-pa-00-alba.webp",
    tier: "a",
    category: "arms",
  },
  {
    name: "IA-C01A: EPHEMERA",
    img: "ia-c01a-ephemera.webp",
    tier: "a",
    category: "arms",
  },
  {
    name: "IB-C03A: HAL 826",
    img: "ib-c03a-hal-826.webp",
    tier: "a",
    category: "arms",
  },
  {
    name: "LG-012 MELANDER C3",
    img: "lg-012-melander-c3.webp",
    tier: "a",
    category: "legs",
  },
  {
    name: "EL-PL-00 ALBA",
    img: "el-pl-00-alba.webp",
    tier: "a",
    category: "legs",
  },
  {
    name: "IA-C01L: EPHEMERA",
    img: "ia-c01l-ephemera.webp",
    tier: "a",
    category: "legs",
  },
  {
    name: "IB-C03L: HAL 826",
    img: "ib-c03l-hal-826.webp",
    tier: "a",
    category: "legs",
  },
  { name: "VE-42B", img: "ve-42b.webp", tier: "a", category: "legs" },
  {
    name: "IA-C01B: GILLS",
    img: "ia-c01b-gills.webp",
    tier: "b",
    category: "booster",
  },
  { name: "VE-21B", img: "ve-21b.webp", tier: "a", category: "fcs" },
  {
    name: "IA-C01F: OCELLUS",
    img: "ia-c01f-ocellus.webp",
    tier: "a",
    category: "fcs",
  },
  {
    name: "IB-C03F: WLT 001",
    img: "ib-c03f-wlt-001.webp",
    tier: "a",
    category: "fcs",
  },
  {
    name: "AG-T-005 HOKUSHI",
    img: "ag-t-005-hokushi.webp",
    tier: "a",
    category: "generator",
  },
  { name: "VE-20C", img: "ve-20c.webp", tier: "b", category: "generator" },
  {
    name: "IB-C03G: NGI 000",
    img: "ib-c03g-ngi-000.webp",
    tier: "a",
    category: "generator",
  },
  {
    name: "LR-037 HARRIS Linear Rifle",
    img: "lr-037-harris.webp",
    tier: "s",
    category: "r-arm",
  },
  {
    name: "RD-025 SCUDDER Assault Rifle",
    img: "rf-025-scudder.webp",
    tier: "d",
    category: "r-arm",
  },
  {
    name: "DF-MG-02 CHANG-CHEN Machine Gun",
    img: "df-mg-02-chang-chen.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "MA-E-210 ETSUJIN Machine Gun",
    img: "ma-e-210-etsujin.webp",
    tier: "s",
    category: "r-arm",
  },
  {
    name: "SG-027 ZIMMERMAN Shotgun",
    img: "sg-027-zimmerman.webp",
    tier: "s",
    category: "r-arm",
  },
  {
    name: "WR-0777 SWEET SIXTEEN Shotgun",
    img: "wr-077-sweet-sixteen.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "HG-004 DUCKETT Handgun",
    img: "hg-004-duckett.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "MA-E-211 SAMPU Burst Handgun",
    img: "ma-e-211-sampu.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "MAJESTIC Bazooka",
    img: "majestic.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "LITTLE GEM Bazooka",
    img: "little-gem.webp",
    tier: "d",
    category: "r-arm",
  },
  {
    name: "MA-T-223 KYORIKU Jamming Bomb Launcher",
    img: "ma-t-223-kyoriku.webp",
    tier: "d",
    category: "r-arm",
  },
  {
    name: "WS-1200 THERAPIST Stun Bomb Launcher",
    img: "ws-1200-therapist.webp",
    tier: "d",
    category: "r-arm",
  },
  {
    name: "WB-0000 BAD COOK Flamethrower",
    img: "wb-0000-bad-cook.webp",
    tier: "d",
    category: "r-arm",
  },
  {
    name: "VE-66LRA Laser Rifle",
    img: "ve-66lra.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "WUERGER/66E Laser Shotgun",
    img: "wuerger-66e.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "IA-C01W1: NEBULA Plasma Rifle",
    img: "ia-c01w1-nebula.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "HI-18: GU-A2 Pulse Gun",
    img: "hi-18-gu-a2.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "PFAU/66D Pulse Missile Launcher",
    img: "pfau66d.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "DF-ET-09 TAI-YANG-SHOU Explosive Thrower",
    img: "df-et-09-tai-yang-shou.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "WB-0010 DOUBLE TROUBLE Chainsaw",
    img: "wb-0010-double-trouble.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "VP-67EB Stun Baton",
    img: "vp-67eb.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "VE-67LLA Laser Lance",
    img: "ve-67lla.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "44-143 HMMR Plasma Thrower",
    img: "44-143-hmmr.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "LR-037 HARRIS Linear Rifle",
    img: "lr-037-harris.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "RD-025 SCUDDER Assault Rifle",
    img: "rf-025-scudder.webp",
    tier: "d",
    category: "l-arm",
  },
  {
    name: "DF-MG-02 CHANG-CHEN Machine Gun",
    img: "df-mg-02-chang-chen.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "MA-E-210 ETSUJIN Machine Gun",
    img: "ma-e-210-etsujin.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "SG-027 ZIMMERMAN Shotgun",
    img: "sg-027-zimmerman.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "WR-0777 SWEET SIXTEEN Shotgun",
    img: "wr-077-sweet-sixteen.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "HG-004 DUCKETT Handgun",
    img: "hg-004-duckett.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "MA-E-211 SAMPU Burst Handgun",
    img: "ma-e-211-sampu.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "MAJESTIC Bazooka",
    img: "majestic.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "LITTLE GEM Bazooka",
    img: "little-gem.webp",
    tier: "d",
    category: "l-arm",
  },
  {
    name: "MA-T-223 KYORIKU Jamming Bomb Launcher",
    img: "ma-t-223-kyoriku.webp",
    tier: "d",
    category: "l-arm",
  },
  {
    name: "WS-1200 THERAPIST Stun Bomb Launcher",
    img: "ws-1200-therapist.webp",
    tier: "d",
    category: "l-arm",
  },
  {
    name: "WB-0000 BAD COOK Flamethrower",
    img: "wb-0000-bad-cook.webp",
    tier: "d",
    category: "l-arm",
  },
  {
    name: "VE-66LRA Laser Rifle",
    img: "ve-66lra.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "WUERGER/66E Laser Shotgun",
    img: "wuerger-66e.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "IA-C01W1: NEBULA Plasma Rifle",
    img: "ia-c01w1-nebula.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "HI-18: GU-A2 Pulse Gun",
    img: "hi-18-gu-a2.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "PFAU/66D Pulse Missile Launcher",
    img: "pfau66d.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "DF-GA-09 SHAO-WEI Gatling Cannon",
    img: "df-ga-09-shao-wei.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "SB-033M MORLEY Spread Bazooka",
    img: "sb-033m-morley.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "VE-60SNA Stun Needle Launcher",
    img: "ve-60sna.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "VP-60LCD Diffuse Laser Cannon",
    img: "vp-60lcd.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "EULE/60D Pulse Shield Launcher",
    img: "eule-60d.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "BML-G2/P03MLT-06 Missile Launcher",
    img: "bml-g2-p03mlt-06.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "BML-G2/P17SPL-16 Split Missile Launcher",
    img: "bml-g1-p17spl-16.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "BML-G1/P32DUO-03 Dual Missile Launcher",
    img: "bml-g1-p32duo-03.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "BML-G3/P05ACT-02 Active Homing Missile Launcher",
    img: "bml-g3-p05act-02.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "45-091 JVLN BETA Detonating Missile Launcher",
    img: "45-091-jvln-beta.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "VP-60LT Laser Turret",
    img: "vp-60lt.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "SI-27: SU-R8 Pulse Shield",
    img: "si-27-su-r8.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "DF-GA-09 SHAO-WEI Gatling Cannon",
    img: "df-ga-09-shao-wei.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "SB-033M MORLEY Spread Bazooka",
    img: "sb-033m-morley.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "VE-60SNA Stun Needle Launcher",
    img: "ve-60sna.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "VP-60LCD Diffuse Laser Cannon",
    img: "vp-60lcd.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "EULE/60D Pulse Shield Launcher",
    img: "eule-60d.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "BML-G2/P03MLT-06 Missile Launcher",
    img: "bml-g2-p03mlt-06.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "BML-G2/P17SPL-16 Split Missile Launcher",
    img: "bml-g1-p17spl-16.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "BML-G1/P32DUO-03 Dual Missile Launcher",
    img: "bml-g1-p32duo-03.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "BML-G3/P05ACT-02 Active Homing Missile Launcher",
    img: "bml-g3-p05act-02.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "45-091 JVLN BETA Detonating Missile Launcher",
    img: "45-091-jvln-beta.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "VP-60LT Laser Turret",
    img: "vp-60lt.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "AH-J-124 BASHO",
    img: "ah-j-124-basho.webp",
    tier: "b",
    category: "head",
  },
  {
    name: "HD-033M VERRILL",
    img: "hd-033m-verrill.webp",
    tier: "s",
    category: "head",
  },
  {
    name: "LAMMERGEIER/44F",
    img: "lammergeier-44f.webp",
    tier: "c",
    category: "head",
  },
  { name: "VE-44A", img: "ve-44a.webp", tier: "b", category: "head" },
  {
    name: "AC-J-120 BASHO",
    img: "ac-j-120-basho.webp",
    tier: "b",
    category: "core",
  },
  {
    name: "LAMMERGEIER/40F",
    img: "lammergeier-40f.webp",
    tier: "b",
    category: "core",
  },
  { name: "VE-40A", img: "ve-40a.webp", tier: "b", category: "core" },
  {
    name: "07-061 MIND ALPHA",
    img: "07-061-mind-alpha.webp",
    tier: "b",
    category: "core",
  },
  {
    name: "AA-J-123 BASHO",
    img: "aa-j-123-basho.webp",
    tier: "b",
    category: "arms",
  },
  {
    name: "LAMMERGEIER/46F",
    img: "lammergeier-46f.webp",
    tier: "b",
    category: "arms",
  },
  { name: "VE-46A", img: "ve-46a.webp", tier: "b", category: "arms" },
  {
    name: "AL-J-121 BASHO",
    img: "al-j-121-basho.webp",
    tier: "b",
    category: "legs",
  },
  { name: "VE-42A", img: "ve-42a.webp", tier: "b", category: "legs" },
  {
    name: "RC-2000 SPRING CHICKEN",
    img: "rc-2000-spring-chicken.webp",
    tier: "b",
    category: "legs",
  },
  {
    name: "06-042 MIND BETA",
    img: "06-042-mind-beta.webp",
    tier: "b",
    category: "legs",
  },
  {
    name: "LG-033M VERRILL",
    img: "lg-033m-verrill.webp",
    tier: "b",
    category: "legs",
  },
  {
    name: "LAMMERGEIER/42F",
    img: "lammergeier-42f.webp",
    tier: "b",
    category: "legs",
  },
  {
    name: "EL-TL-11 FORTALEZA",
    img: "el-tl-11-fortaleza.webp",
    tier: "b",
    category: "legs",
  },
  {
    name: "BST-G2/P06SPD",
    img: "bst-g2-p06spd.webp",
    tier: "b",
    category: "booster",
  },
  {
    name: "FLUEGEL 21/Z",
    img: "fluegel-21z.webp",
    tier: "a",
    category: "booster",
  },
  {
    name: "BC-0600 12345",
    img: "bc-0600-12345.webp",
    tier: "b",
    category: "booster",
  },
  {
    name: "BC-0400 MULE",
    img: "bc-0400-mule.webp",
    tier: "d",
    category: "booster",
  },
  {
    name: "FCS-G2/P12SML",
    img: "fcs-g2-p12sml.webp",
    tier: "b",
    category: "fcs",
  },
  { name: "VE-21A", img: "ve-21a.webp", tier: "b", category: "fcs" },
  {
    name: "DF-GN-08 SAN-TAI",
    img: "df-gn-08-san-tai.webp",
    tier: "b",
    category: "generator",
  },
  { name: "VP-20C", img: "vp-20c.webp", tier: "b", category: "generator" },
  { name: "VE-20A", img: "ve-20a.webp", tier: "b", category: "generator" },
  {
    name: "IA-C01G: AORTA",
    img: "ia-c01g-aorta.webp",
    tier: "c",
    category: "generator",
  },
  {
    name: "MA-J-201 RANSETSU-AR Burst Assault Rifle",
    img: "ma-j-201-ransetsu-ar.webp",
    tier: "c",
    category: "r-arm",
  },
  {
    name: "DF-GA-08 HU-BEN Gatling Gun",
    img: "df-ga-08-hu-ben.webp",
    tier: "s",
    category: "r-arm",
  },
  {
    name: "SG-026 HALDEMAN Shotgun",
    img: "sg-026-haldeman.webp",
    tier: "a",
    category: "r-arm",
  },
  {
    name: "44-141 JVLN ALPHA Detonating Bazooka",
    img: "44-141-jvln-alpha.webp",
    tier: "a",
    category: "r-arm",
  },
  {
    name: "DF-GR-07 GOU-CHEN Grenade Launcher",
    img: "df-gr-07-gou-chen.webp",
    tier: "c",
    category: "r-arm",
  },
  {
    name: "IRIDIUM Grenade Launcher",
    img: "iridium.webp",
    tier: "c",
    category: "r-arm",
  },
  {
    name: "MA-T-222 KYORAI Napalm Bomb Launcher",
    img: "ma-t-223-kyoriku.webp",
    tier: "d",
    category: "r-arm",
  },
  {
    name: "VP-66LR Laser Rifle",
    img: "vp-66lr.webp",
    tier: "c",
    category: "r-arm",
  },
  {
    name: "VP-66LS Laser Shotgun",
    img: "vp-66ls.webp",
    tier: "c",
    category: "r-arm",
  },
  {
    name: "VP-66LH Laser Handgun",
    img: "vp-66lh.webp",
    tier: "c",
    category: "r-arm",
  },
  {
    name: "Vvc-760PR Plasma Rifle",
    img: "vvc-760pr.webp",
    tier: "c",
    category: "r-arm",
  },
  {
    name: "HI-16: GU-Q1 Pulse Gun",
    img: "hi-16-gu-q1.webp",
    tier: "c",
    category: "r-arm",
  },
  {
    name: "HML-G2/P19MLT-04 Missile Launcher",
    img: "hml-g2-p19mlt-04.webp",
    tier: "c",
    category: "r-arm",
  },
  {
    name: "PB-033M ASHMEAD Pile Bunker",
    img: "pb-033m-ashmead.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "Vvc-770LB Laser Blade",
    img: "vvc-770lb.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "MA-J-201 RANSETSU-AR Burst Assault Rifle",
    img: "ma-j-201-ransetsu-ar.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "DF-GA-08 HU-BEN Gatling Gun",
    img: "df-ga-08-hu-ben.webp",
    tier: "s",
    category: "l-arm",
  },
  {
    name: "SG-026 HALDEMAN Shotgun",
    img: "sg-026-haldeman.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "44-141 JVLN ALPHA Detonating Bazooka",
    img: "44-141-jvln-alpha.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "DF-GR-07 GOU-CHEN Grenade Launcher",
    img: "df-gr-07-gou-chen.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "IRIDIUM Grenade Launcher",
    img: "iridium.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "MA-T-222 KYORAI Napalm Bomb Launcher",
    img: "ma-t-223-kyoriku.webp",
    tier: "d",
    category: "l-arm",
  },
  {
    name: "VP-66LR Laser Rifle",
    img: "vp-66lr.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "VP-66LS Laser Shotgun",
    img: "vp-66ls.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "VP-66LH Laser Handgun",
    img: "vp-66lh.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "Vvc-760PR Plasma Rifle",
    img: "vvc-760pr.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "HI-16: GU-Q1 Pulse Gun",
    img: "hi-16-gu-q1.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "HML-G2/P19MLT-04 Missile Launcher",
    img: "hml-g2-p19mlt-04.webp",
    tier: "c",
    category: "l-arm",
  },
  {
    name: "SONGBIRDS Grenade Cannon",
    img: "songbirds.webp",
    tier: "s",
    category: "r-back",
  },
  {
    name: "VP-60LCS Laser Cannon",
    img: "vp-60lcs.webp",
    tier: "c",
    category: "r-back",
  },
  {
    name: "MLT-10 Missile Launcher",
    img: "bml-g2-p05mlt-10.webp",
    tier: "c",
    category: "r-back",
  },
  {
    name: "BML-G2/P16SPL-08 Split Missile Launcher",
    img: "bml-g2-p16spl-08.webp",
    tier: "c",
    category: "r-back",
  },
  {
    name: "BML-G1/P01VTC-04 Vertical Missile Launcher",
    img: "bml-g1-p01vtc-04.webp",
    tier: "d",
    category: "r-back",
  },
  {
    name: "BML-G1/P03VTC-08 Vertical Missile Launcher",
    img: "bml-g1-p03vtc-08.webp",
    tier: "d",
    category: "r-back",
  },
  {
    name: "BML-G3/P04ACT-01 Active Homing Missile Launcher",
    img: "bml-g3-p04act-01.webp",
    tier: "c",
    category: "r-back",
  },
  {
    name: "Vvc-703PM Plasma Missile Launcher",
    img: "vvc-703pm.webp",
    tier: "a",
    category: "r-back",
  },
  {
    name: "Vvc-706VPM Plasma Missile Launcher",
    img: "vvc-706pm.webp",
    tier: "a",
    category: "r-back",
  },
  {
    name: "VP-61PS Pulse Shield",
    img: "vp-61ps.webp",
    tier: "c",
    category: "l-back",
  },
  {
    name: "VP-61PB Pulse Buckler",
    img: "vp-61pb.webp",
    tier: "c",
    category: "l-back",
  },
  {
    name: "SI-29: SU-TT/C Pulse Buckler",
    img: "si-29-su-tt-c.webp",
    tier: "d",
    category: "l-back",
  },
  {
    name: "SONGBIRDS Grenade Cannon",
    img: "songbirds.webp",
    tier: "s",
    category: "l-back",
  },
  {
    name: "VP-60LCS Laser Cannon",
    img: "vp-60lcs.webp",
    tier: "c",
    category: "l-back",
  },
  {
    name: "BML-G2/P05MLT-10 Missile Launcher",
    img: "bml-g2-p05mlt-10.webp",
    tier: "c",
    category: "l-back",
  },
  {
    name: "BML-G2/P16SPL-08 Split Missile Launcher",
    img: "bml-g2-p16spl-08.webp",
    tier: "c",
    category: "l-back",
  },
  {
    name: "BML-G1/P01VTC-04 Vertical Missile Launcher",
    img: "bml-g1-p01vtc-04.webp",
    tier: "d",
    category: "l-back",
  },
  {
    name: "BML-G1/P03VTC-08 Vertical Missile Launcher",
    img: "bml-g1-p03vtc-08.webp",
    tier: "d",
    category: "l-back",
  },
  {
    name: "BML-G3/P04ACT-01 Active Homing Missile Launcher",
    img: "bml-g3-p04act-01.webp",
    tier: "c",
    category: "l-back",
  },
  {
    name: "Vvc-703PM Plasma Missile Launcher",
    img: "vvc-703pm.webp",
    tier: "a",
    category: "l-back",
  },
  {
    name: "Vvc-706VPM Plasma Missile Launcher",
    img: "vvc-706pm.webp",
    tier: "a",
    category: "l-back",
  },
  { name: "KASUAR/44Z", img: "kasuar-44z.webp", tier: "c", category: "head" },
  {
    name: "HC-3000 WRECKER",
    img: "hc-3000-wrecker.webp",
    tier: "c",
    category: "head",
  },
  {
    name: "EL-TH-10 FIRMEZA",
    img: "el-th-10-firmeza.webp",
    tier: "c",
    category: "head",
  },
  {
    name: "CC-3000 WRECKER",
    img: "cc-3000-wrecker.webp",
    tier: "c",
    category: "core",
  },
  {
    name: "EL-TC-10 FIRMEZA",
    img: "el-tc-10-firmeza.webp",
    tier: "c",
    category: "core",
  },
  {
    name: "DF-AR-09 TIAN-LAO",
    img: "df-ar-09-tian-lao.webp",
    tier: "c",
    category: "arms",
  },
  {
    name: "AC-3000 WRECKER",
    img: "ac-3000-wrecker.webp",
    tier: "c",
    category: "arms",
  },
  {
    name: "EL-TA-10 FIRMEZA",
    img: "el-ta-10-firmeza.webp",
    tier: "c",
    category: "arms",
  },
  {
    name: "04-101 MIND ALPHA",
    img: "04-101-mind-alpha.webp",
    tier: "c",
    category: "arms",
  },
  {
    name: "2C-3000 WRECKER",
    img: "2c-3000-wrecker.webp",
    tier: "c",
    category: "legs",
  },
  {
    name: "EL-TL-10 FIRMEZA",
    img: "el-tl-10-firmeza.webp",
    tier: "c",
    category: "legs",
  },
  {
    name: "06-041 MIND ALPHA",
    img: "06-041-mind-alpha.webp",
    tier: "c",
    category: "legs",
  },
  { name: "KASUAR/42Z", img: "kasuar-42z.webp", tier: "c", category: "legs" },
  { name: "VP-424", img: "vp-424.webp", tier: "c", category: "legs" },
  {
    name: "LG-022T BORNEMISSZA",
    img: "lg-022t-bornemissza.webp",
    tier: "c",
    category: "legs",
  },
  {
    name: "AB-J-137 KIKAKU",
    img: "ab-j-137-kikaku.webp",
    tier: "c",
    category: "booster",
  },
  { name: "ALULA/21E", img: "alula-21e.webp", tier: "s", category: "booster" },
  {
    name: "BUERZEL/21D",
    img: "buerzel-21d.webp",
    tier: "b",
    category: "booster",
  },
  { name: "FCS-G2/P05", img: "fcs-g2-p05.webp", tier: "c", category: "fcs" },
  {
    name: "FC-006 ABBOT",
    img: "fc-006-abbot.webp",
    tier: "c",
    category: "fcs",
  },
  {
    name: "FC-008 TALBOT",
    img: "fc-008-talbot.webp",
    tier: "c",
    category: "fcs",
  },
  {
    name: "AG-E-013 YABA",
    img: "ag-e-013-yaba.webp",
    tier: "a",
    category: "generator",
  },
  {
    name: "DF-GN-06 MING-TANG",
    img: "df-gn-06-ming-tai.webp",
    tier: "a",
    category: "generator",
  },
  { name: "VP-20S", img: "vp-20s.webp", tier: "s", category: "generator" },
  { name: "VP-20D", img: "vp-20d.webp", tier: "b", category: "generator" },
  // {
  //   name: "BST-G1/P10",
  //   img: "bst-g1-p10.webp",
  //   tier: "d",
  //   category: "booster",
  // },
  // {
  //   name: "AG-J-098 JOSO",
  //   img: "ag-j-098-joso.webp",
  //   tier: "d",
  //   category: "generator",
  // },
  // { name: "FCS-G1/P01", img: "fcs-g1-p01.webp", tier: "d", category: "fcs" },
  {
    name: "MA-J-200 RANSETSU-RF Burst Rifle",
    img: "ma-j-200-ransetsu-rf.webp",
    tier: "d",
    category: "r-arm",
  },
  {
    name: "LR-036 CURTIS Linear Rifle",
    img: "lr-036-curtis.webp",
    tier: "a",
    category: "r-arm",
  },
  {
    name: "RF-024 TURNER Assault Rifle",
    img: "rf-024-turner.webp",
    tier: "d",
    category: "r-arm",
  },
  {
    name: "MG-014 LUDLOW Machine Gun",
    img: "mg-014-ludlow.webp",
    tier: "a",
    category: "r-arm",
  },
  {
    name: "HG-003 COQUILLETT Handgun",
    img: "hg-003-coquillett.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "DF-BA-06 XUAN-GE Bazooka",
    img: "df-ba-06-xuan-ge.webp",
    tier: "b",
    category: "r-arm",
  },
  {
    name: "HI-32 BU/TT-A Pulse Blade",
    img: "hi-32-bu-tt-a.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "MA-J-200 RANSETSU-RF Burst Rifle",
    img: "ma-j-200-ransetsu-rf.webp",
    tier: "d",
    category: "l-arm",
  },
  {
    name: "LR-036 CURTIS Linear Rifle",
    img: "lr-036-curtis.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "RF-024 TURNER Assault Rifle",
    img: "rf-024-turner.webp",
    tier: "d",
    category: "l-arm",
  },
  {
    name: "MG-014 LUDLOW Machine Gun",
    img: "mg-014-ludlow.webp",
    tier: "a",
    category: "l-arm",
  },
  {
    name: "HG-003 COQUILLETT Handgun",
    img: "hg-003-coquillett.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "DF-BA-06 XUAN-GE Bazooka",
    img: "df-ba-06-xuan-ge.webp",
    tier: "b",
    category: "l-arm",
  },
  {
    name: "BML-G1/P20MLT-04 Missile Launcher",
    img: "bml-g1-p20mlt-04.webp",
    tier: "b",
    category: "r-back",
  },
  {
    name: "BML-G1/P31DUO-02 Dual Missile Launcher",
    img: "bml-g1-p31duo-02.webp",
    tier: "d",
    category: "r-back",
  },
  {
    name: "SI-24: SU-Q5 Pulse Shield",
    img: "si-24-su-q5.webp",
    tier: "d",
    category: "l-back",
  },
  {
    name: "BML-G1/P20MLT-04 Missile Launcher",
    img: "bml-g1-p20mlt-04.webp",
    tier: "b",
    category: "l-back",
  },
  {
    name: "BML-G1/P31DUO-02 Dual Missile Launcher",
    img: "bml-g1-p31duo-02.webp",
    tier: "d",
    category: "l-back",
  },
  {
    name: "HD-011 MELANDER",
    img: "hd-011-melander.webp",
    tier: "d",
    category: "head",
  },
  {
    name: "DF-HD-08 TIAN-QIANG",
    img: "df-hd-08-tian-qiang.webp",
    tier: "c",
    category: "head",
  },
  { name: "VP-44S", img: "vp-44s.webp", tier: "d", category: "head" },
  {
    name: "NACHTREIHER/44E",
    img: "nachtreiher-44e.webp",
    tier: "d",
    category: "head",
  },
  {
    name: "HC-2000 FINDER EYE",
    img: "hc-2000-finder-eye.webp",
    tier: "d",
    category: "head",
  },
  {
    name: "BD-011 MELANDER",
    img: "bd-011-melander.webp",
    tier: "d",
    category: "core",
  },
  {
    name: "DF-BD-08 TIAN-QIANG",
    img: "df-bd-08-tian-qiang.webp",
    tier: "d",
    category: "core",
  },
  { name: "VP-40S", img: "vp-40s.webp", tier: "d", category: "core" },
  {
    name: "NACHTREIHER/40E",
    img: "nachtreiher-40e.webp",
    tier: "d",
    category: "core",
  },
  {
    name: "CC-2000 ORBITER",
    img: "cc-2000-orbiter.webp",
    tier: "d",
    category: "core",
  },
  {
    name: "AR-011 MELANDER",
    img: "ar-011-melander.webp",
    tier: "d",
    category: "arms",
  },
  {
    name: "DF-AR-08 TIAN-QIANG",
    img: "df-ar-08-tian-qiang.webp",
    tier: "d",
    category: "arms",
  },
  { name: "VP-46S", img: "vp-46s.webp", tier: "d", category: "arms" },
  {
    name: "NACHTREIHER/46E",
    img: "nachtreiher-46e.webp",
    tier: "d",
    category: "arms",
  },
  {
    name: "AC-2000 TOOL ARM",
    img: "ac-2000-tool-arm.webp",
    tier: "d",
    category: "arms",
  },
  {
    name: "LG-011 MELANDER",
    img: "lg-011-melander.webp",
    tier: "d",
    category: "legs",
  },
  {
    name: "DF-LG-08 TIAN-QIANG",
    img: "df-lg08-tian-qiang.webp",
    tier: "d",
    category: "legs",
  },
  { name: "VP-422", img: "vp-422.webp", tier: "d", category: "legs" },
  {
    name: "NACHTREIHER/42E",
    img: "nachtreiher-42e.webp",
    tier: "d",
    category: "legs",
  },
  {
    name: "2C-2000 CRAWLER",
    img: "2c-2000-crawler.webp",
    tier: "d",
    category: "legs",
  },
  {
    name: "BST-G2/P04",
    img: "bst-g2-p04.webp",
    tier: "c",
    category: "booster",
  },
  {
    name: "FCS-G2/P10SLT",
    img: "fcs-g2-p10slt.webp",
    tier: "d",
    category: "fcs",
  },
  {
    name: "DF-GN-02 LING-TAI",
    img: "df-gn-02-ling-tai.webp",
    tier: "d",
    category: "generator",
  },
];
